### ISSUE TITLE
[BE-05] Product Mock 데이터 수집

### ISSUE THREAD

**Issue by geunhokinn** [Step3-kakao-tech-campus/Team15_BE#12]
## 작업 내용

- [x] Product Mock 데이터 수집 (현재 대여 가능한 상품만)
* 이름
* 렌탈가 (월)
* 정가
* 카테고리
* 내용
* 배달 불가능 지역 여부
* 참조 사이트

**Comment by zxc88kr** [comment]
이슈 열린게 너무 많아서 일단 닫아두겠습니다 ! 고생하셧써용
나중에 시간날 때 조금 더 추가해주세요
