### ISSUE TITLE
[BE-19] category, university id 타입 변경

### ISSUE THREAD

**Issue by C0Zl** [Step3-kakao-tech-campus/Team15_BE#44]
## 작업 내용
- [ ] category, university id 타입 Long -> int 변경

## 기타
- category와 university 객체의 경우 id 타입을 Long으로 사용하는 것이 비효율적이기 때문에 int로 변경할 예정입니다. 
- merge 후 일괄적으로 수정할 예정입니다.

**Comment by zxc88kr** [comment]
추후 리팩토링 한꺼번에 진행하겠습니다.

**Comment by zxc88kr** [comment]
https://github.com/Step3-kakao-tech-campus/Team15_BE/issues/83 중복된 내용이라 이슈 닫겠습니다.
