### ISSUE TITLE
[BE-04] API 실패 예시 에러코드 수정

### ISSUE THREAD

**Issue by C0Zl** [Step3-kakao-tech-campus/Team15_BE#8]
### API 실패 예시 에러코드 수정
- [x] API response : code -> reason 수정
- [x] API 커스텀 에러 표 제작
  - message
  - status : 400 -> 최대한 유사한 걸로 변경
  - reason : 일관성 있게 수정
- [x] github 이슈 수정
- [x] 작업한 user entity pr

## 작업 예시

before
```
{
	"success": false, 
	"response": null,
	"error": { 
		"message": "로그인이 되어 있지 않습니다.:user",
		"status": 400,
		"code": "logout_01_not_logined"
	}
}
```
after
```
{
	"success": false, 
	"response": null,
	"error": { 
		"message": "로그인 되어 있지 않습니다.",
		"status": 401,
		"reason": "logout_not_logined"
	}
}
```
[노션 링크
](https://www.notion.so/loopy-lim/BE_API-c02e5946141b45f889a22cb909d0d617)

## Reference
[Web API의 에러를 어떻게 표현해야 할까? (1)
](https://velog.io/@josworks27/Web-API%EC%9D%98-%EC%97%90%EB%9F%AC%EB%A5%BC-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%91%9C%ED%98%84%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C-1
)

## etc
10/2 짧은 회의 후 역할 분담을 다시 설정하였습니다.

**Comment by zxc88kr** [comment]
고생하셨습니다 이슈 닫도록 하겠습니다
